# Site settings
title: Dan Wilcox
#email: your-email@domain.com
url: https://dwilcox8.github.io/
#url: https://localhost:4000/
description: "Dan Wilcox - Computer Systems Engineer and Front-End Developer"
meta_author: Wilcox Dan 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
##disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000; #036266 #'18bc9c
  primary-rgb: 000; #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  skill-set: E86612 #ff7821

# Footer settings
footer:
  copyright: Dan Wilcox
  location: Vancouver, BC
  social: Around the Web
  #credits: Freelancer Theme 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/dwilcox8
  - title: linkedin
    url:  http://www.linkedin.com/in/dan-wilcox-5652074b


# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
